# Generated by Django 5.1.2 on 2024-11-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fuliza'),
    ]

    operations = [
        migrations.CreateModel(
            name='MShwari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
