# Generated by Django 5.1.2 on 2024-11-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mshwari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mshwari',
            old_name='balance',
            new_name='available_balance',
        ),
    ]
